" Minimal vimrc for VSCode-Neovim integration
" This file focuses on ensuring leader key works

" Set <Space> as the leader key
let mapleader = " "
let maplocalleader = " "

" Prevent space from acting as forward
nnoremap <SPACE> <Nop>
vnoremap <SPACE> <Nop>

" Explicitly map Space+key combinations for VSCode commands
" Test commands - matching your nvim keybindings
nnoremap <silent> <leader>test <Cmd>call VSCodeNotify('workbench.action.showInformationMessage', 'Leader key test is working!')<CR>
nnoremap <silent> <leader>tz <Cmd>call VSCodeNotify('workbench.action.toggleZenMode')<CR>
nnoremap <silent> <leader>sk <Cmd>call VSCodeNotify('workbench.action.openGlobalKeybindings')<CR>

" Search commands
nnoremap <silent> <leader>sf <Cmd>call VSCodeNotify('workbench.action.quickOpen')<CR>
nnoremap <silent> <leader>sg <Cmd>call VSCodeNotify('workbench.action.findInFiles')<CR>
nnoremap <silent> <leader><leader> <Cmd>call VSCodeNotify('workbench.action.showAllEditorsByMostRecentlyUsed')<CR>

" Common features
nnoremap <silent> <leader>tt <Cmd>call VSCodeNotify('workbench.action.toggleTerminal')<CR>
nnoremap <silent> <leader>e <Cmd>call VSCodeNotify('workbench.view.explorer')<CR>

" Set timeoutlen to be short enough for leader key
set timeoutlen=500

" Allow clipboard integration
set clipboard=unnamedplus 